spring:
  application:
    name: zuul
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
      hostname: localhost

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: user
    api-b:
      path: /api/b/**
      serviceId: feign