spring:
  application:
    name: user
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    hostname: localhost
#    允许多个实例
#    metadata-map:
#      instanceId:  ${spring.application.name}:${random.value}