server:
  port: 8090
#  设置 session 的过期时间
#  servlet:
#    session:
#      timeout: PT30S
spring:
  application:
    name: authority
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/authority?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 5683
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
#    关闭缓存
    cache: false
  jpa:
    database: mysql
#    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
#  redis
#  redis:
#    host: 120.78.189.213
#    port: 6379
#    password: 123456
#    database: 0
#   使用 redis 实现 session 共享
#  session:
#    redis:
#      namespace: redis:session
#      flush-mode: on_save
#    store-type: redis
#    timeout: 5m
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

