server:
  port: 8090

spring:
  application:
    name: authority
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/bill?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Root5683@
    driver-class-name: com.mysql.cj.jdbc.Driver
