server:
  # 服务端口
  port: 8090

#h2配置
#启用SQL语句的日志记录
spring:
  jpa:
    show-sql: true
  #设置ddl模式
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
  ##数据库连接设置
  datasource:
    driverClassName: org.h2.Driver
  #可执行程序的当前路径
#    url: jdbc:h2:mem:test
    url: jdbc:h2:file:D:/tools/development/h2/db/student
  #指定的静态配置路径
    username: h2
    password: h2
  ##数据初始化设置
  #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
#    schema: classpath:db/schema.sql
  #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
#    data: classpath:db/data.sql
  ##h2 web console设置
  #表明使用的数据库平台是h2
    platform: h2
  # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
  h2:
    console:
      settings:
        web-allow-others: true
  #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      path: /h2
  #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      enabled: true