spring:
  application:
    name: hystrix
server:
  port: 8070
eureka:
  instance:
    hostname: localhost
    instance-id: Register
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
#feign:
#  hystrix:
#    enabled: true
