spring:
  application:
    name: eureka
server:
  port: 8000
#  因为当前的 eureka 是单机的所以需要一些配置
eureka:
  instance:
    hostname: localhost
  client:
#    申明这是一个 eureka 服务
    register-with-eureka: false
    registry-fetch-interval-seconds: 10000
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

